# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Poga\Desktop\painis\tram-sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Poga\Desktop\painis\tram-sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Poga\Desktop\painis\tram-sdk\CMakeFiles C:\Users\Poga\Desktop\painis\tram-sdk\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Poga\Desktop\painis\tram-sdk\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tram-library

# Build rule for target.
tram-library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tram-library
.PHONY : tram-library

# fast build rule for target.
tram-library/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/build
.PHONY : tram-library/fast

src/audio/audio.obj: src/audio/audio.cpp.obj
.PHONY : src/audio/audio.obj

# target to build an object file
src/audio/audio.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/audio/audio.cpp.obj
.PHONY : src/audio/audio.cpp.obj

src/audio/audio.i: src/audio/audio.cpp.i
.PHONY : src/audio/audio.i

# target to preprocess a source file
src/audio/audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/audio/audio.cpp.i
.PHONY : src/audio/audio.cpp.i

src/audio/audio.s: src/audio/audio.cpp.s
.PHONY : src/audio/audio.s

# target to generate assembly for a file
src/audio/audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/audio/audio.cpp.s
.PHONY : src/audio/audio.cpp.s

src/components/armaturecomponent.obj: src/components/armaturecomponent.cpp.obj
.PHONY : src/components/armaturecomponent.obj

# target to build an object file
src/components/armaturecomponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/armaturecomponent.cpp.obj
.PHONY : src/components/armaturecomponent.cpp.obj

src/components/armaturecomponent.i: src/components/armaturecomponent.cpp.i
.PHONY : src/components/armaturecomponent.i

# target to preprocess a source file
src/components/armaturecomponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/armaturecomponent.cpp.i
.PHONY : src/components/armaturecomponent.cpp.i

src/components/armaturecomponent.s: src/components/armaturecomponent.cpp.s
.PHONY : src/components/armaturecomponent.s

# target to generate assembly for a file
src/components/armaturecomponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/armaturecomponent.cpp.s
.PHONY : src/components/armaturecomponent.cpp.s

src/components/controllercomponent.obj: src/components/controllercomponent.cpp.obj
.PHONY : src/components/controllercomponent.obj

# target to build an object file
src/components/controllercomponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/controllercomponent.cpp.obj
.PHONY : src/components/controllercomponent.cpp.obj

src/components/controllercomponent.i: src/components/controllercomponent.cpp.i
.PHONY : src/components/controllercomponent.i

# target to preprocess a source file
src/components/controllercomponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/controllercomponent.cpp.i
.PHONY : src/components/controllercomponent.cpp.i

src/components/controllercomponent.s: src/components/controllercomponent.cpp.s
.PHONY : src/components/controllercomponent.s

# target to generate assembly for a file
src/components/controllercomponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/controllercomponent.cpp.s
.PHONY : src/components/controllercomponent.cpp.s

src/components/entitycomponents.obj: src/components/entitycomponents.cpp.obj
.PHONY : src/components/entitycomponents.obj

# target to build an object file
src/components/entitycomponents.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/entitycomponents.cpp.obj
.PHONY : src/components/entitycomponents.cpp.obj

src/components/entitycomponents.i: src/components/entitycomponents.cpp.i
.PHONY : src/components/entitycomponents.i

# target to preprocess a source file
src/components/entitycomponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/entitycomponents.cpp.i
.PHONY : src/components/entitycomponents.cpp.i

src/components/entitycomponents.s: src/components/entitycomponents.cpp.s
.PHONY : src/components/entitycomponents.s

# target to generate assembly for a file
src/components/entitycomponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/entitycomponents.cpp.s
.PHONY : src/components/entitycomponents.cpp.s

src/components/particlecomponent.obj: src/components/particlecomponent.cpp.obj
.PHONY : src/components/particlecomponent.obj

# target to build an object file
src/components/particlecomponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/particlecomponent.cpp.obj
.PHONY : src/components/particlecomponent.cpp.obj

src/components/particlecomponent.i: src/components/particlecomponent.cpp.i
.PHONY : src/components/particlecomponent.i

# target to preprocess a source file
src/components/particlecomponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/particlecomponent.cpp.i
.PHONY : src/components/particlecomponent.cpp.i

src/components/particlecomponent.s: src/components/particlecomponent.cpp.s
.PHONY : src/components/particlecomponent.s

# target to generate assembly for a file
src/components/particlecomponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/particlecomponent.cpp.s
.PHONY : src/components/particlecomponent.cpp.s

src/components/rendercomponent.obj: src/components/rendercomponent.cpp.obj
.PHONY : src/components/rendercomponent.obj

# target to build an object file
src/components/rendercomponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/rendercomponent.cpp.obj
.PHONY : src/components/rendercomponent.cpp.obj

src/components/rendercomponent.i: src/components/rendercomponent.cpp.i
.PHONY : src/components/rendercomponent.i

# target to preprocess a source file
src/components/rendercomponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/rendercomponent.cpp.i
.PHONY : src/components/rendercomponent.cpp.i

src/components/rendercomponent.s: src/components/rendercomponent.cpp.s
.PHONY : src/components/rendercomponent.s

# target to generate assembly for a file
src/components/rendercomponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/rendercomponent.cpp.s
.PHONY : src/components/rendercomponent.cpp.s

src/components/spritecomponent.obj: src/components/spritecomponent.cpp.obj
.PHONY : src/components/spritecomponent.obj

# target to build an object file
src/components/spritecomponent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/spritecomponent.cpp.obj
.PHONY : src/components/spritecomponent.cpp.obj

src/components/spritecomponent.i: src/components/spritecomponent.cpp.i
.PHONY : src/components/spritecomponent.i

# target to preprocess a source file
src/components/spritecomponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/spritecomponent.cpp.i
.PHONY : src/components/spritecomponent.cpp.i

src/components/spritecomponent.s: src/components/spritecomponent.cpp.s
.PHONY : src/components/spritecomponent.s

# target to generate assembly for a file
src/components/spritecomponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/components/spritecomponent.cpp.s
.PHONY : src/components/spritecomponent.cpp.s

src/entities/crate.obj: src/entities/crate.cpp.obj
.PHONY : src/entities/crate.obj

# target to build an object file
src/entities/crate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/crate.cpp.obj
.PHONY : src/entities/crate.cpp.obj

src/entities/crate.i: src/entities/crate.cpp.i
.PHONY : src/entities/crate.i

# target to preprocess a source file
src/entities/crate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/crate.cpp.i
.PHONY : src/entities/crate.cpp.i

src/entities/crate.s: src/entities/crate.cpp.s
.PHONY : src/entities/crate.s

# target to generate assembly for a file
src/entities/crate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/crate.cpp.s
.PHONY : src/entities/crate.cpp.s

src/entities/lamp.obj: src/entities/lamp.cpp.obj
.PHONY : src/entities/lamp.obj

# target to build an object file
src/entities/lamp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/lamp.cpp.obj
.PHONY : src/entities/lamp.cpp.obj

src/entities/lamp.i: src/entities/lamp.cpp.i
.PHONY : src/entities/lamp.i

# target to preprocess a source file
src/entities/lamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/lamp.cpp.i
.PHONY : src/entities/lamp.cpp.i

src/entities/lamp.s: src/entities/lamp.cpp.s
.PHONY : src/entities/lamp.s

# target to generate assembly for a file
src/entities/lamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/lamp.cpp.s
.PHONY : src/entities/lamp.cpp.s

src/entities/player.obj: src/entities/player.cpp.obj
.PHONY : src/entities/player.obj

# target to build an object file
src/entities/player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/player.cpp.obj
.PHONY : src/entities/player.cpp.obj

src/entities/player.i: src/entities/player.cpp.i
.PHONY : src/entities/player.i

# target to preprocess a source file
src/entities/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/player.cpp.i
.PHONY : src/entities/player.cpp.i

src/entities/player.s: src/entities/player.cpp.s
.PHONY : src/entities/player.s

# target to generate assembly for a file
src/entities/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/player.cpp.s
.PHONY : src/entities/player.cpp.s

src/entities/staticworldobject.obj: src/entities/staticworldobject.cpp.obj
.PHONY : src/entities/staticworldobject.obj

# target to build an object file
src/entities/staticworldobject.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/staticworldobject.cpp.obj
.PHONY : src/entities/staticworldobject.cpp.obj

src/entities/staticworldobject.i: src/entities/staticworldobject.cpp.i
.PHONY : src/entities/staticworldobject.i

# target to preprocess a source file
src/entities/staticworldobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/staticworldobject.cpp.i
.PHONY : src/entities/staticworldobject.cpp.i

src/entities/staticworldobject.s: src/entities/staticworldobject.cpp.s
.PHONY : src/entities/staticworldobject.s

# target to generate assembly for a file
src/entities/staticworldobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/entities/staticworldobject.cpp.s
.PHONY : src/entities/staticworldobject.cpp.s

src/extensions/menu/menu.obj: src/extensions/menu/menu.cpp.obj
.PHONY : src/extensions/menu/menu.obj

# target to build an object file
src/extensions/menu/menu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/extensions/menu/menu.cpp.obj
.PHONY : src/extensions/menu/menu.cpp.obj

src/extensions/menu/menu.i: src/extensions/menu/menu.cpp.i
.PHONY : src/extensions/menu/menu.i

# target to preprocess a source file
src/extensions/menu/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/extensions/menu/menu.cpp.i
.PHONY : src/extensions/menu/menu.cpp.i

src/extensions/menu/menu.s: src/extensions/menu/menu.cpp.s
.PHONY : src/extensions/menu/menu.s

# target to generate assembly for a file
src/extensions/menu/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/extensions/menu/menu.cpp.s
.PHONY : src/extensions/menu/menu.cpp.s

src/framework/async.obj: src/framework/async.cpp.obj
.PHONY : src/framework/async.obj

# target to build an object file
src/framework/async.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/async.cpp.obj
.PHONY : src/framework/async.cpp.obj

src/framework/async.i: src/framework/async.cpp.i
.PHONY : src/framework/async.i

# target to preprocess a source file
src/framework/async.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/async.cpp.i
.PHONY : src/framework/async.cpp.i

src/framework/async.s: src/framework/async.cpp.s
.PHONY : src/framework/async.s

# target to generate assembly for a file
src/framework/async.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/async.cpp.s
.PHONY : src/framework/async.cpp.s

src/framework/core.obj: src/framework/core.cpp.obj
.PHONY : src/framework/core.obj

# target to build an object file
src/framework/core.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/core.cpp.obj
.PHONY : src/framework/core.cpp.obj

src/framework/core.i: src/framework/core.cpp.i
.PHONY : src/framework/core.i

# target to preprocess a source file
src/framework/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/core.cpp.i
.PHONY : src/framework/core.cpp.i

src/framework/core.s: src/framework/core.cpp.s
.PHONY : src/framework/core.s

# target to generate assembly for a file
src/framework/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/core.cpp.s
.PHONY : src/framework/core.cpp.s

src/framework/entity.obj: src/framework/entity.cpp.obj
.PHONY : src/framework/entity.obj

# target to build an object file
src/framework/entity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/entity.cpp.obj
.PHONY : src/framework/entity.cpp.obj

src/framework/entity.i: src/framework/entity.cpp.i
.PHONY : src/framework/entity.i

# target to preprocess a source file
src/framework/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/entity.cpp.i
.PHONY : src/framework/entity.cpp.i

src/framework/entity.s: src/framework/entity.cpp.s
.PHONY : src/framework/entity.s

# target to generate assembly for a file
src/framework/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/entity.cpp.s
.PHONY : src/framework/entity.cpp.s

src/framework/etc.obj: src/framework/etc.cpp.obj
.PHONY : src/framework/etc.obj

# target to build an object file
src/framework/etc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/etc.cpp.obj
.PHONY : src/framework/etc.cpp.obj

src/framework/etc.i: src/framework/etc.cpp.i
.PHONY : src/framework/etc.i

# target to preprocess a source file
src/framework/etc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/etc.cpp.i
.PHONY : src/framework/etc.cpp.i

src/framework/etc.s: src/framework/etc.cpp.s
.PHONY : src/framework/etc.s

# target to generate assembly for a file
src/framework/etc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/etc.cpp.s
.PHONY : src/framework/etc.cpp.s

src/framework/event.obj: src/framework/event.cpp.obj
.PHONY : src/framework/event.obj

# target to build an object file
src/framework/event.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/event.cpp.obj
.PHONY : src/framework/event.cpp.obj

src/framework/event.i: src/framework/event.cpp.i
.PHONY : src/framework/event.i

# target to preprocess a source file
src/framework/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/event.cpp.i
.PHONY : src/framework/event.cpp.i

src/framework/event.s: src/framework/event.cpp.s
.PHONY : src/framework/event.s

# target to generate assembly for a file
src/framework/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/event.cpp.s
.PHONY : src/framework/event.cpp.s

src/framework/gui.obj: src/framework/gui.cpp.obj
.PHONY : src/framework/gui.obj

# target to build an object file
src/framework/gui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/gui.cpp.obj
.PHONY : src/framework/gui.cpp.obj

src/framework/gui.i: src/framework/gui.cpp.i
.PHONY : src/framework/gui.i

# target to preprocess a source file
src/framework/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/gui.cpp.i
.PHONY : src/framework/gui.cpp.i

src/framework/gui.s: src/framework/gui.cpp.s
.PHONY : src/framework/gui.s

# target to generate assembly for a file
src/framework/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/gui.cpp.s
.PHONY : src/framework/gui.cpp.s

src/framework/logging.obj: src/framework/logging.cpp.obj
.PHONY : src/framework/logging.obj

# target to build an object file
src/framework/logging.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/logging.cpp.obj
.PHONY : src/framework/logging.cpp.obj

src/framework/logging.i: src/framework/logging.cpp.i
.PHONY : src/framework/logging.i

# target to preprocess a source file
src/framework/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/logging.cpp.i
.PHONY : src/framework/logging.cpp.i

src/framework/logging.s: src/framework/logging.cpp.s
.PHONY : src/framework/logging.s

# target to generate assembly for a file
src/framework/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/logging.cpp.s
.PHONY : src/framework/logging.cpp.s

src/framework/math.obj: src/framework/math.cpp.obj
.PHONY : src/framework/math.obj

# target to build an object file
src/framework/math.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/math.cpp.obj
.PHONY : src/framework/math.cpp.obj

src/framework/math.i: src/framework/math.cpp.i
.PHONY : src/framework/math.i

# target to preprocess a source file
src/framework/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/math.cpp.i
.PHONY : src/framework/math.cpp.i

src/framework/math.s: src/framework/math.cpp.s
.PHONY : src/framework/math.s

# target to generate assembly for a file
src/framework/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/math.cpp.s
.PHONY : src/framework/math.cpp.s

src/framework/message.obj: src/framework/message.cpp.obj
.PHONY : src/framework/message.obj

# target to build an object file
src/framework/message.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/message.cpp.obj
.PHONY : src/framework/message.cpp.obj

src/framework/message.i: src/framework/message.cpp.i
.PHONY : src/framework/message.i

# target to preprocess a source file
src/framework/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/message.cpp.i
.PHONY : src/framework/message.cpp.i

src/framework/message.s: src/framework/message.cpp.s
.PHONY : src/framework/message.s

# target to generate assembly for a file
src/framework/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/message.cpp.s
.PHONY : src/framework/message.cpp.s

src/framework/navigation.obj: src/framework/navigation.cpp.obj
.PHONY : src/framework/navigation.obj

# target to build an object file
src/framework/navigation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/navigation.cpp.obj
.PHONY : src/framework/navigation.cpp.obj

src/framework/navigation.i: src/framework/navigation.cpp.i
.PHONY : src/framework/navigation.i

# target to preprocess a source file
src/framework/navigation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/navigation.cpp.i
.PHONY : src/framework/navigation.cpp.i

src/framework/navigation.s: src/framework/navigation.cpp.s
.PHONY : src/framework/navigation.s

# target to generate assembly for a file
src/framework/navigation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/navigation.cpp.s
.PHONY : src/framework/navigation.cpp.s

src/framework/net.obj: src/framework/net.cpp.obj
.PHONY : src/framework/net.obj

# target to build an object file
src/framework/net.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/net.cpp.obj
.PHONY : src/framework/net.cpp.obj

src/framework/net.i: src/framework/net.cpp.i
.PHONY : src/framework/net.i

# target to preprocess a source file
src/framework/net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/net.cpp.i
.PHONY : src/framework/net.cpp.i

src/framework/net.s: src/framework/net.cpp.s
.PHONY : src/framework/net.s

# target to generate assembly for a file
src/framework/net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/net.cpp.s
.PHONY : src/framework/net.cpp.s

src/framework/stats.obj: src/framework/stats.cpp.obj
.PHONY : src/framework/stats.obj

# target to build an object file
src/framework/stats.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/stats.cpp.obj
.PHONY : src/framework/stats.cpp.obj

src/framework/stats.i: src/framework/stats.cpp.i
.PHONY : src/framework/stats.i

# target to preprocess a source file
src/framework/stats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/stats.cpp.i
.PHONY : src/framework/stats.cpp.i

src/framework/stats.s: src/framework/stats.cpp.s
.PHONY : src/framework/stats.s

# target to generate assembly for a file
src/framework/stats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/stats.cpp.s
.PHONY : src/framework/stats.cpp.s

src/framework/system.obj: src/framework/system.cpp.obj
.PHONY : src/framework/system.obj

# target to build an object file
src/framework/system.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/system.cpp.obj
.PHONY : src/framework/system.cpp.obj

src/framework/system.i: src/framework/system.cpp.i
.PHONY : src/framework/system.i

# target to preprocess a source file
src/framework/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/system.cpp.i
.PHONY : src/framework/system.cpp.i

src/framework/system.s: src/framework/system.cpp.s
.PHONY : src/framework/system.s

# target to generate assembly for a file
src/framework/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/system.cpp.s
.PHONY : src/framework/system.cpp.s

src/framework/ui.obj: src/framework/ui.cpp.obj
.PHONY : src/framework/ui.obj

# target to build an object file
src/framework/ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/ui.cpp.obj
.PHONY : src/framework/ui.cpp.obj

src/framework/ui.i: src/framework/ui.cpp.i
.PHONY : src/framework/ui.i

# target to preprocess a source file
src/framework/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/ui.cpp.i
.PHONY : src/framework/ui.cpp.i

src/framework/ui.s: src/framework/ui.cpp.s
.PHONY : src/framework/ui.s

# target to generate assembly for a file
src/framework/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/ui.cpp.s
.PHONY : src/framework/ui.cpp.s

src/framework/uid.obj: src/framework/uid.cpp.obj
.PHONY : src/framework/uid.obj

# target to build an object file
src/framework/uid.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/uid.cpp.obj
.PHONY : src/framework/uid.cpp.obj

src/framework/uid.i: src/framework/uid.cpp.i
.PHONY : src/framework/uid.i

# target to preprocess a source file
src/framework/uid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/uid.cpp.i
.PHONY : src/framework/uid.cpp.i

src/framework/uid.s: src/framework/uid.cpp.s
.PHONY : src/framework/uid.s

# target to generate assembly for a file
src/framework/uid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/uid.cpp.s
.PHONY : src/framework/uid.cpp.s

src/framework/worldcell.obj: src/framework/worldcell.cpp.obj
.PHONY : src/framework/worldcell.obj

# target to build an object file
src/framework/worldcell.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/worldcell.cpp.obj
.PHONY : src/framework/worldcell.cpp.obj

src/framework/worldcell.i: src/framework/worldcell.cpp.i
.PHONY : src/framework/worldcell.i

# target to preprocess a source file
src/framework/worldcell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/worldcell.cpp.i
.PHONY : src/framework/worldcell.cpp.i

src/framework/worldcell.s: src/framework/worldcell.cpp.s
.PHONY : src/framework/worldcell.s

# target to generate assembly for a file
src/framework/worldcell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/framework/worldcell.cpp.s
.PHONY : src/framework/worldcell.cpp.s

src/physics/collisionmodel.obj: src/physics/collisionmodel.cpp.obj
.PHONY : src/physics/collisionmodel.obj

# target to build an object file
src/physics/collisionmodel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/collisionmodel.cpp.obj
.PHONY : src/physics/collisionmodel.cpp.obj

src/physics/collisionmodel.i: src/physics/collisionmodel.cpp.i
.PHONY : src/physics/collisionmodel.i

# target to preprocess a source file
src/physics/collisionmodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/collisionmodel.cpp.i
.PHONY : src/physics/collisionmodel.cpp.i

src/physics/collisionmodel.s: src/physics/collisionmodel.cpp.s
.PHONY : src/physics/collisionmodel.s

# target to generate assembly for a file
src/physics/collisionmodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/collisionmodel.cpp.s
.PHONY : src/physics/collisionmodel.cpp.s

src/physics/physics.obj: src/physics/physics.cpp.obj
.PHONY : src/physics/physics.obj

# target to build an object file
src/physics/physics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/physics.cpp.obj
.PHONY : src/physics/physics.cpp.obj

src/physics/physics.i: src/physics/physics.cpp.i
.PHONY : src/physics/physics.i

# target to preprocess a source file
src/physics/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/physics.cpp.i
.PHONY : src/physics/physics.cpp.i

src/physics/physics.s: src/physics/physics.cpp.s
.PHONY : src/physics/physics.s

# target to generate assembly for a file
src/physics/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/physics/physics.cpp.s
.PHONY : src/physics/physics.cpp.s

src/platform/file.obj: src/platform/file.cpp.obj
.PHONY : src/platform/file.obj

# target to build an object file
src/platform/file.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/platform/file.cpp.obj
.PHONY : src/platform/file.cpp.obj

src/platform/file.i: src/platform/file.cpp.i
.PHONY : src/platform/file.i

# target to preprocess a source file
src/platform/file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/platform/file.cpp.i
.PHONY : src/platform/file.cpp.i

src/platform/file.s: src/platform/file.cpp.s
.PHONY : src/platform/file.s

# target to generate assembly for a file
src/platform/file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/platform/file.cpp.s
.PHONY : src/platform/file.cpp.s

src/render/armature.obj: src/render/armature.cpp.obj
.PHONY : src/render/armature.obj

# target to build an object file
src/render/armature.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/armature.cpp.obj
.PHONY : src/render/armature.cpp.obj

src/render/armature.i: src/render/armature.cpp.i
.PHONY : src/render/armature.i

# target to preprocess a source file
src/render/armature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/armature.cpp.i
.PHONY : src/render/armature.cpp.i

src/render/armature.s: src/render/armature.cpp.s
.PHONY : src/render/armature.s

# target to generate assembly for a file
src/render/armature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/armature.cpp.s
.PHONY : src/render/armature.cpp.s

src/render/material.obj: src/render/material.cpp.obj
.PHONY : src/render/material.obj

# target to build an object file
src/render/material.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/material.cpp.obj
.PHONY : src/render/material.cpp.obj

src/render/material.i: src/render/material.cpp.i
.PHONY : src/render/material.i

# target to preprocess a source file
src/render/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/material.cpp.i
.PHONY : src/render/material.cpp.i

src/render/material.s: src/render/material.cpp.s
.PHONY : src/render/material.s

# target to generate assembly for a file
src/render/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/material.cpp.s
.PHONY : src/render/material.cpp.s

src/render/model.obj: src/render/model.cpp.obj
.PHONY : src/render/model.obj

# target to build an object file
src/render/model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/model.cpp.obj
.PHONY : src/render/model.cpp.obj

src/render/model.i: src/render/model.cpp.i
.PHONY : src/render/model.i

# target to preprocess a source file
src/render/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/model.cpp.i
.PHONY : src/render/model.cpp.i

src/render/model.s: src/render/model.cpp.s
.PHONY : src/render/model.s

# target to generate assembly for a file
src/render/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/model.cpp.s
.PHONY : src/render/model.cpp.s

src/render/opengl/renderer.obj: src/render/opengl/renderer.cpp.obj
.PHONY : src/render/opengl/renderer.obj

# target to build an object file
src/render/opengl/renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/renderer.cpp.obj
.PHONY : src/render/opengl/renderer.cpp.obj

src/render/opengl/renderer.i: src/render/opengl/renderer.cpp.i
.PHONY : src/render/opengl/renderer.i

# target to preprocess a source file
src/render/opengl/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/renderer.cpp.i
.PHONY : src/render/opengl/renderer.cpp.i

src/render/opengl/renderer.s: src/render/opengl/renderer.cpp.s
.PHONY : src/render/opengl/renderer.s

# target to generate assembly for a file
src/render/opengl/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/renderer.cpp.s
.PHONY : src/render/opengl/renderer.cpp.s

src/render/opengl/shader.obj: src/render/opengl/shader.cpp.obj
.PHONY : src/render/opengl/shader.obj

# target to build an object file
src/render/opengl/shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/shader.cpp.obj
.PHONY : src/render/opengl/shader.cpp.obj

src/render/opengl/shader.i: src/render/opengl/shader.cpp.i
.PHONY : src/render/opengl/shader.i

# target to preprocess a source file
src/render/opengl/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/shader.cpp.i
.PHONY : src/render/opengl/shader.cpp.i

src/render/opengl/shader.s: src/render/opengl/shader.cpp.s
.PHONY : src/render/opengl/shader.s

# target to generate assembly for a file
src/render/opengl/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/opengl/shader.cpp.s
.PHONY : src/render/opengl/shader.cpp.s

src/render/render.obj: src/render/render.cpp.obj
.PHONY : src/render/render.obj

# target to build an object file
src/render/render.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render.cpp.obj
.PHONY : src/render/render.cpp.obj

src/render/render.i: src/render/render.cpp.i
.PHONY : src/render/render.i

# target to preprocess a source file
src/render/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render.cpp.i
.PHONY : src/render/render.cpp.i

src/render/render.s: src/render/render.cpp.s
.PHONY : src/render/render.s

# target to generate assembly for a file
src/render/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render.cpp.s
.PHONY : src/render/render.cpp.s

src/render/render_misc.obj: src/render/render_misc.cpp.obj
.PHONY : src/render/render_misc.obj

# target to build an object file
src/render/render_misc.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render_misc.cpp.obj
.PHONY : src/render/render_misc.cpp.obj

src/render/render_misc.i: src/render/render_misc.cpp.i
.PHONY : src/render/render_misc.i

# target to preprocess a source file
src/render/render_misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render_misc.cpp.i
.PHONY : src/render/render_misc.cpp.i

src/render/render_misc.s: src/render/render_misc.cpp.s
.PHONY : src/render/render_misc.s

# target to generate assembly for a file
src/render/render_misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/render_misc.cpp.s
.PHONY : src/render/render_misc.cpp.s

src/render/renderer.obj: src/render/renderer.cpp.obj
.PHONY : src/render/renderer.obj

# target to build an object file
src/render/renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/renderer.cpp.obj
.PHONY : src/render/renderer.cpp.obj

src/render/renderer.i: src/render/renderer.cpp.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

src/render/sprite.obj: src/render/sprite.cpp.obj
.PHONY : src/render/sprite.obj

# target to build an object file
src/render/sprite.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/sprite.cpp.obj
.PHONY : src/render/sprite.cpp.obj

src/render/sprite.i: src/render/sprite.cpp.i
.PHONY : src/render/sprite.i

# target to preprocess a source file
src/render/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/sprite.cpp.i
.PHONY : src/render/sprite.cpp.i

src/render/sprite.s: src/render/sprite.cpp.s
.PHONY : src/render/sprite.s

# target to generate assembly for a file
src/render/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\tram-library.dir\build.make CMakeFiles/tram-library.dir/src/render/sprite.cpp.s
.PHONY : src/render/sprite.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... tram-library
	@echo ... src/audio/audio.obj
	@echo ... src/audio/audio.i
	@echo ... src/audio/audio.s
	@echo ... src/components/armaturecomponent.obj
	@echo ... src/components/armaturecomponent.i
	@echo ... src/components/armaturecomponent.s
	@echo ... src/components/controllercomponent.obj
	@echo ... src/components/controllercomponent.i
	@echo ... src/components/controllercomponent.s
	@echo ... src/components/entitycomponents.obj
	@echo ... src/components/entitycomponents.i
	@echo ... src/components/entitycomponents.s
	@echo ... src/components/particlecomponent.obj
	@echo ... src/components/particlecomponent.i
	@echo ... src/components/particlecomponent.s
	@echo ... src/components/rendercomponent.obj
	@echo ... src/components/rendercomponent.i
	@echo ... src/components/rendercomponent.s
	@echo ... src/components/spritecomponent.obj
	@echo ... src/components/spritecomponent.i
	@echo ... src/components/spritecomponent.s
	@echo ... src/entities/crate.obj
	@echo ... src/entities/crate.i
	@echo ... src/entities/crate.s
	@echo ... src/entities/lamp.obj
	@echo ... src/entities/lamp.i
	@echo ... src/entities/lamp.s
	@echo ... src/entities/player.obj
	@echo ... src/entities/player.i
	@echo ... src/entities/player.s
	@echo ... src/entities/staticworldobject.obj
	@echo ... src/entities/staticworldobject.i
	@echo ... src/entities/staticworldobject.s
	@echo ... src/extensions/menu/menu.obj
	@echo ... src/extensions/menu/menu.i
	@echo ... src/extensions/menu/menu.s
	@echo ... src/framework/async.obj
	@echo ... src/framework/async.i
	@echo ... src/framework/async.s
	@echo ... src/framework/core.obj
	@echo ... src/framework/core.i
	@echo ... src/framework/core.s
	@echo ... src/framework/entity.obj
	@echo ... src/framework/entity.i
	@echo ... src/framework/entity.s
	@echo ... src/framework/etc.obj
	@echo ... src/framework/etc.i
	@echo ... src/framework/etc.s
	@echo ... src/framework/event.obj
	@echo ... src/framework/event.i
	@echo ... src/framework/event.s
	@echo ... src/framework/gui.obj
	@echo ... src/framework/gui.i
	@echo ... src/framework/gui.s
	@echo ... src/framework/logging.obj
	@echo ... src/framework/logging.i
	@echo ... src/framework/logging.s
	@echo ... src/framework/math.obj
	@echo ... src/framework/math.i
	@echo ... src/framework/math.s
	@echo ... src/framework/message.obj
	@echo ... src/framework/message.i
	@echo ... src/framework/message.s
	@echo ... src/framework/navigation.obj
	@echo ... src/framework/navigation.i
	@echo ... src/framework/navigation.s
	@echo ... src/framework/net.obj
	@echo ... src/framework/net.i
	@echo ... src/framework/net.s
	@echo ... src/framework/stats.obj
	@echo ... src/framework/stats.i
	@echo ... src/framework/stats.s
	@echo ... src/framework/system.obj
	@echo ... src/framework/system.i
	@echo ... src/framework/system.s
	@echo ... src/framework/ui.obj
	@echo ... src/framework/ui.i
	@echo ... src/framework/ui.s
	@echo ... src/framework/uid.obj
	@echo ... src/framework/uid.i
	@echo ... src/framework/uid.s
	@echo ... src/framework/worldcell.obj
	@echo ... src/framework/worldcell.i
	@echo ... src/framework/worldcell.s
	@echo ... src/physics/collisionmodel.obj
	@echo ... src/physics/collisionmodel.i
	@echo ... src/physics/collisionmodel.s
	@echo ... src/physics/physics.obj
	@echo ... src/physics/physics.i
	@echo ... src/physics/physics.s
	@echo ... src/platform/file.obj
	@echo ... src/platform/file.i
	@echo ... src/platform/file.s
	@echo ... src/render/armature.obj
	@echo ... src/render/armature.i
	@echo ... src/render/armature.s
	@echo ... src/render/material.obj
	@echo ... src/render/material.i
	@echo ... src/render/material.s
	@echo ... src/render/model.obj
	@echo ... src/render/model.i
	@echo ... src/render/model.s
	@echo ... src/render/opengl/renderer.obj
	@echo ... src/render/opengl/renderer.i
	@echo ... src/render/opengl/renderer.s
	@echo ... src/render/opengl/shader.obj
	@echo ... src/render/opengl/shader.i
	@echo ... src/render/opengl/shader.s
	@echo ... src/render/render.obj
	@echo ... src/render/render.i
	@echo ... src/render/render.s
	@echo ... src/render/render_misc.obj
	@echo ... src/render/render_misc.i
	@echo ... src/render/render_misc.s
	@echo ... src/render/renderer.obj
	@echo ... src/render/renderer.i
	@echo ... src/render/renderer.s
	@echo ... src/render/sprite.obj
	@echo ... src/render/sprite.i
	@echo ... src/render/sprite.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

