// TRAMWAY DRIFT AND DUNGEON EXPLORATION SIMULATOR 2022
// All rights reserved.

#ifndef TRAM_SDK_EXTENSIONS_CAMERA_THIRDPERSON_H
#define TRAM_SDK_EXTENSIONS_CAMERA_THIRDPERSON_H

#include <extensions/camera/camera.h>

namespace tram::Ext::Camera {

}

#endif // TRAM_SDK_EXTENSIONS_CAMERA_THIRDPERSON_H